name: Artifacts
main: io.github.rm2023.Artifacts.Main
version: 1.0
api-version: "1.15"
commands:
   artifactAdmin:
      description: Command for managing artifacts as an admin
   passives:
      description: Command for managing passives as a player